# 嵌套子模块可见性配置
# 格式：父目录|相对路径|public 或 private
# 空行和 # 开头行会被忽略。修改后运行 init_repo.sh 即可生效。
#
# robot-descriptions
src/robot-descriptions|common|public
src/robot-descriptions|manipulator/Dobot|public
src/robot-descriptions|manipulator/ARX|public
src/robot-descriptions|quadruped|public
src/robot-descriptions|manipulator/Tianji|private
src/robot-descriptions|manipulator/Rokae|private
src/robot-descriptions|humanoid/FiveAges/fiveages_w1_description|private
src/robot-descriptions|humanoid/FiveAges/fiveages_w2_description|private
src/robot-descriptions|humanoid/Ubtech|private
#
# arms_ros2_control
# src/arms_ros2_control|hardwares/marvin_ros2_control|public
# src/arms_ros2_control|hardwares/unitree_ros2_control|public
# src/arms_ros2_control|hardwares/dobot_ros2_control|public
# src/arms_ros2_control|hardwares/modbus_ros2_control|public
# src/arms_ros2_control|hardwares/arx_ros2_control|public
# src/arms_ros2_control|hardwares/rokae_ros2_control|private
# src/arms_ros2_control|hardwares/eyou_ros2_control|private
src/arms_ros2_control|libraries/lina_planning|private
src/arms_ros2_control|libraries/ocs2_humanoid|private
#
# ocs2_ros2
src/ocs2_ros2|submodules/ocs2_robotic_assets|public
# src/ocs2_ros2|submodules/plane_segmentation_ros2|public
